name: study Video
description: Template for a video blog.
url: 'https://wblearn.github.io/study-video/'
baseurl: '/study-video'
email: 1275660493@qq.com
weibo: https://weibo.com/5717080324
twitter: https://twitter.com/wblearn1
youtube: https://www.youtube.com/wblearn713
google_analytics: 'UA-00000000-1'

################################################################
################################################################
encoding: utf-8
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video